intento de agregar el json
pybalt/uade-algo1-tp-integrador pull request #42
Opened 2024-10-23 23:41 UTC by tomasliberi

intento de implementacion de json

2024-10-24 03:11 UTC, pybalt requested changes
Por ahora arreglá lo que te comenté, después hacemos testing evaluando la funcionalidad

2024-10-24 03:11 UTC, pybalt commented on __main__.py
> +if _name_ == "_main_":
`__name__` nunca va a poder ser `_main_`

[Pequeño articulo](https://www.freecodecamp.org/news/whats-in-a-python-s-name-506262fe61e8/#:~:text=The%20__name__%20variable%20(two%20underscores%20before%20and%20after,a%20module%20in%20another%20script.)

2024-10-24 03:11 UTC, pybalt commented on __main__.py
> +    database.fill_directory()  # Llenar el directorio al iniciar la aplicación
llamada ok, comentario innecesario

2024-10-24 03:11 UTC, pybalt commented on database/__init__.py
> +from utils.json_handling import save_to_json
good aproach

2024-10-24 03:11 UTC, pybalt commented on database/directory.py
> +    global _directory
`global _directory`
Evita usar la keyword `global` lo mas que puedas
mejor recibir esa variable por parametro

2024-10-24 03:11 UTC, pybalt commented on database/directory.py
> +    _directory = json_handling.load_from_json()  # Cargar la base de datos desde JSON
comentario innecesario, el nombre de la funcion ya es auto explicativa

2024-10-29 02:06 UTC, pybalt requested changes

2024-10-29 02:06 UTC, pybalt commented on database/directory.py
> +def get_directory(directory):
Esta funcion es una paradoja

Para poder devolver el directorio, necesita recibir por parámetro el directorio que tiene que devolverte

2024-10-29 02:06 UTC, pybalt commented on database/directory.py
> -_directory = {}
La idea de esta variable es que sea modificada por fill_directory, pero oculta a otros modulos, entonces para acceder a ella tendrias que usar get_directory

Otra forma es que get_directory lea recursivamente todas las carpetas, con una logica similar a json_handling.load_from_json, pero sería demasiado costoso innecesariamente

2024-11-09 00:56 UTC, Pabloravioli approved these changes

2024-11-09 02:57 UTC, pybalt approved these changes

2024-11-09 02:58 UTC, merged